### ISSUE TITLE
Invalid memory address  or nil pointer: mem.go

### ISSUE THREAD

**Issue by dangerousHobo** [zombiezen/go-capnproto2#57]
My go-capnproto2 package is up-to-date. When I run a small example with capnproto it gets an error. All code can be found [here](https://gist.github.com/dangerousHobo/2caf41d9705ac51cb48c349d4ade831a).

The error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x84ab4]

goroutine 1 [running]:
panic(0x106138, 0x1040a010)
        /home/mjohn/software/go/src/runtime/panic.go:500 +0x33c
zombiezen.com/go/capnproto2.alloc(0x0, 0x18, 0x0, 0x0, 0x0, 0x0)
        /home/mjohn/workspaces/goprojects/src/zombiezen.com/go/capnproto2/mem.go:264 +0x7c
zombiezen.com/go/capnproto2.NewStruct(0x0, 0x0, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/mjohn/workspaces/goprojects/src/zombiezen.com/go/capnproto2/struct.go:18 +0x128
crown/fram/imm.NewVehicle(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/mjohn/workspaces/goprojects/src/crown/fram/imm/schema.capnp.go:581 +0x5c
crown/fram/imm.Fram.NewVehicle(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/mjohn/workspaces/goprojects/src/crown/fram/imm/schema.capnp.go:1050 +0x7c
main.main()
        /home/mjohn/workspaces/goprojects/src/crown/fram/imm/utils/wr.go:25 +0x29c
```

**Comment by zombiezen** [comment]
Your line numbers are slightly off, so I'm going to assume that `main()` crashes on the NewVehicle line.  I think this is WAI, since you are attempting to write something to a null Cap'n Proto pointer (only reading is allowed).  You want to use `immfram.NewRootFram` on main.go:18.

**Comment by dangerousHobo** [comment]
Yes, using ReadRootFram instead of NewRootFram was my issue. Thanks for the help!
